# -*- coding: utf-8 -*-
"""main_rungekutta_multivar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sSdGdMNuQTa5rDS_zCCKfyVvoElMFITh
"""

from sympy import *
from math import *
import sys


from lib_rungekutta import *

"""# Phương pháp Runge - Kutta hiện giải bài toán Cauchy cho hệ phương trình vi phân

## 0. Bài toán

Giải hệ phương trình vi phân $r$ phương trình sau:

$$\begin{cases} \frac{dy_{1}}{dx} = f_{1}(x, y_{1}, y_{2}, ...., y_{r})\\\frac{dy_{2}}{dx} = f_{2}(x, y_{1}, y_{2}, ...., y_{r})\\.... \\\frac{dy_{r}}{dx} = f_{r}(x, y_{1}, y_{2}, ...., y_{r})\end{cases}$$

Ta có thể xây dựng lại như sau:

$$\frac{dY}{dx} = F(x, Y)$$

## 1. Nhập dữ liệu

Nhập hệ phương trình $\frac{dY}{dx} = F(x, Y)$, với $x$ thuộc giá trị thực, $Y$ là vector các nghiệm ${y_{i}}$
"""

def expr(x, y):
#{
    dy = np.zeros((len(y)))

    n = y[0]
    p = y[1]
    K = 100
    r = 0.6
    a = 0.04
    muy = 1.2

    dy[0] = r * n * (1 - n / K) - a * n * p
    dy[1] = -muy * p + a * n * p
    return dy
#}

"""Nhập giá trị ban đầu $x_{0}$ và $Y(x_{0})$"""

x_0 = 0
y_0 = [70, 20]

"""Nhập khoảng cách giữa 2 điểm liên tiếp $h = x_{i} - x_{i-1}$"""

h = 0.1

"""Nhập số mốc của lưới điểm $n$ """

n = 1000

"""## 2. Giải PTVP và in ra kết quả
Cấp chính xác:
"""

precision_x   = 3;
precision_y   = 7;
precision_eps = 12;

"""Giải và in kết quả. Kết quả trả về là dạng `list`, mỗi phần tử có cấu trúc sau:
$$ [x_{i}, Y_{i} = [y_{1}(x_{i}), y_{2}(x_{i}), ..., y_{r}(x_{i})]] $$
với $y_{k}(x_{i})$ là giá trị hàm số $y_{k}$ tại điểm $x_{i}$

"""

uu      = rungekutta_multivariate_oop(expr, x_0, y_0, h, n);
ketqua  = (uu.Solve());

print(f"Phương pháp Runge-Kutta {4} nấc với hoàn tất với lưới điểm sau, sai số toàn cục O(h^{4}) = {round(h**4, precision_eps)}:");
#}
for x in ketqua: print(round(x[0], precision_x), x[1]);

"""## 3. Đồ thị
### 3.1. Đồ thị liên hệ giữa các biến $y_{i}$ và $x$
"""

y1  = [];
y2  = [];
y3  = [];
y4  = [];
x   = [];

for xx in ketqua: x.append(xx[0]);
for xx in ketqua: y1.append(xx[1][0]), y2.append(xx[1][1]);

plt.plot(x, y1, 'r')
plt.plot(x, y2, 'b')
plt.legend(["Con mồi", "Thú săn mồi"], loc=1)

plt.xlabel('Thời gian', fontsize=17)
plt.ylabel('Số lượng thú', fontsize=17)
plt.tight_layout()
plt.show()

"""### 3.2.Đồ thị liên hệ giữa các $y_{i}$:"""

y1  = [];
y2  = [];
y3  = [];
y4  = [];
x   = [];

for xx in ketqua: x.append(xx[0]);
for xx in ketqua: y1.append(xx[1][0]), y2.append(xx[1][1]);
plt.xlabel('con mồi', fontsize=15)
plt.ylabel('thú săn mồi', fontsize=15)

plt.plot(y1, y2, 'r')
plt.tight_layout()
plt.show()

